version: "3"
services:
  postgres_reading:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    restart: always
    container_name: postgres_reading
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    networks:
      - expense-tracker

  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres_reading
    networks:
      - expense-tracker

volumes:
  postgres_volume:

networks:
  expense-tracker:
